### ISSUE TITLE
License for code and pretrained models needs clarification

### ISSUE THREAD

**Issue by mayjs** [trougnouf/nind-denoise#8]
Hi, I'm experimenting with building a small NCNN or TFLite based CLI tool based on your excellent work here.

Unfortunately I don't see license information in the repository.
Could you clarify the license under which you offer the code and your pretrained models?

**Comment by trougnouf** [comment]
Thank you for bringing this to my attention, I've added the GPL3 license to the project.

**Comment by mayjs** [comment]
Hey, just wanted to get to you about this.
First of all, thanks for adding the license!

I've started to work on a utility to run your models using Vulkan GPU acceleration.
If you want to take a look: https://github.com/mayjs/NeuraTable

The next step for me is to figure out a way to ship the pretrained models - don't want them checked into the Git repository, so I'm thinking about creating releases with the checkpoints and ONNX files in my fork of nind-denoise.
